"""AI Insights endpoints."""
import json
from typing import List

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.core.deps import get_current_user
from app.core.redis import redis_client
from app.db.session import get_db
from app.models.models import Employee, User
from app.routers._employee_helpers import DETAIL_RELATIONSHIPS, to_employee_detail
from app.schemas.schemas import AIInsightResponse, AIQuery
from app.services.ai_service import (
    analyze_promotion_readiness,
    answer_team_question,
    generate_employee_summary,
    identify_team_insights,
)

router = APIRouter()

TEAM_INSIGHTS_CACHE_KEY = "team-insights:v1"
TEAM_INSIGHTS_TTL_SECONDS = 3600


async def _load_team_data(db: AsyncSession, employee_ids: List[str] | None = None) -> list[dict]:
    query = select(Employee).options(*DETAIL_RELATIONSHIPS)
    if employee_ids:
        query = query.where(Employee.id.in_(employee_ids))
    result = await db.execute(query)
    employees = result.scalars().all()
    team_data = []
    for e in employees:
        detail = to_employee_detail(e)
        team_data.append(detail.model_dump(mode="json"))
    return team_data


@router.get("/", response_model=List[AIInsightResponse])
async def get_team_insights(db: AsyncSession = Depends(get_db), _user: User = Depends(get_current_user)):
    """
    Return proactively identified team insights.
    Generated by AI service analyzing team performance data.
    Cached for 1 hour, refreshed on data change.
    """
    cached = await redis_client.get(TEAM_INSIGHTS_CACHE_KEY)
    if cached:
        return json.loads(cached)

    team_data = await _load_team_data(db)
    insights = await identify_team_insights(team_data)
    await redis_client.set(TEAM_INSIGHTS_CACHE_KEY, json.dumps(insights, default=str), ex=TEAM_INSIGHTS_TTL_SECONDS)
    return insights


@router.post("/ask")
async def ask_team_question(
    query: AIQuery, db: AsyncSession = Depends(get_db), _user: User = Depends(get_current_user)
):
    """
    Answer a natural language question about the team.
    Example: "Who needs coaching?" / "Who is ready for promotion?"
    """
    team_data = await _load_team_data(db, query.employee_ids)
    answer = await answer_team_question(query.question, {"employees": team_data, "context": query.context})
    return {"answer": answer}


@router.post("/employee/{employee_id}/promotion-analysis")
async def analyze_promotion(
    employee_id: str, db: AsyncSession = Depends(get_db), _user: User = Depends(get_current_user)
):
    """
    Deep promotion readiness analysis for a specific employee.
    Returns: readiness level, evidence, gaps, and recommended timeline.
    """
    query = select(Employee).options(*DETAIL_RELATIONSHIPS, selectinload(Employee.role_profile)).where(
        Employee.id == employee_id
    )
    result = await db.execute(query)
    employee = result.scalar_one_or_none()
    if employee is None:
        raise HTTPException(404, "Employee not found")

    employee.tags = employee.tags or []
    employee_data = to_employee_detail(employee).model_dump(mode="json")
    next_level_criteria = (
        {
            "breadth_target": employee.role_profile.breadth_target,
            "depth_target": employee.role_profile.depth_target,
            "depth_skill_ids": employee.role_profile.depth_skill_ids,
        }
        if employee.role_profile
        else {}
    )
    return await analyze_promotion_readiness(employee_data, next_level_criteria)


@router.post("/employee/{employee_id}/summary")
async def generate_summary(
    employee_id: str,
    period: str = "quarterly",
    db: AsyncSession = Depends(get_db),
    _user: User = Depends(get_current_user),
):
    """
    Generate AI-powered performance summary.
    Suitable for performance review documentation.
    """
    query = select(Employee).options(*DETAIL_RELATIONSHIPS).where(Employee.id == employee_id)
    result = await db.execute(query)
    employee = result.scalar_one_or_none()
    if employee is None:
        raise HTTPException(404, "Employee not found")

    employee.tags = employee.tags or []
    employee_data = to_employee_detail(employee).model_dump(mode="json")
    summary = await generate_employee_summary(employee_data, period=period)
    return {"summary": summary}
