"""AI Insights endpoints."""
import json
from typing import List

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

import hashlib

from app.core.deps import get_scope, require_employee_access
from app.core.rbac import Scope
from app.core.redis import redis_client
from app.db.session import get_db
from app.models.models import Employee
from app.routers._employee_helpers import DETAIL_RELATIONSHIPS, to_employee_detail
from app.schemas.schemas import AIInsightResponse, AIQuery
from app.services.ai_service import (
    analyze_promotion_readiness,
    answer_team_question,
    generate_employee_summary,
    identify_team_insights,
)

router = APIRouter()

TEAM_INSIGHTS_TTL_SECONDS = 3600


def _insights_cache_key(scope: Scope) -> str:
    """Cache insights per distinct scope.

    A single global key would serve one organization's generated insights to the
    next caller regardless of what they are allowed to see — a leak through the
    cache even once the queries themselves are scoped. Hashing the visible id set
    means two users with identical visibility share an entry and nobody else does.
    """
    if scope.unrestricted:
        return "team-insights:v2:all"
    digest = hashlib.sha256(",".join(sorted(scope.employee_ids)).encode()).hexdigest()[:32]
    return f"team-insights:v2:{digest}"


async def _load_team_data(
    db: AsyncSession, scope: Scope, employee_ids: List[str] | None = None
) -> list[dict]:
    """Load full profiles for the AI prompt, never widening past the caller's scope."""
    query = select(Employee).options(*DETAIL_RELATIONSHIPS)
    if employee_ids:
        scope.assert_can_view_employees(employee_ids)
        query = query.where(Employee.id.in_(employee_ids))
    elif not scope.unrestricted:
        if not scope.employee_ids:
            return []
        query = query.where(Employee.id.in_(scope.employee_ids))
    result = await db.execute(query)
    employees = result.scalars().all()
    team_data = []
    for e in employees:
        detail = to_employee_detail(e)
        team_data.append(detail.model_dump(mode="json"))
    return team_data


@router.get("/", response_model=List[AIInsightResponse])
async def get_team_insights(db: AsyncSession = Depends(get_db), scope: Scope = Depends(get_scope)):
    """
    Return proactively identified team insights.
    Generated by AI service analyzing team performance data.
    Cached for 1 hour, refreshed on data change.
    """
    cache_key = _insights_cache_key(scope)
    cached = await redis_client.get(cache_key)
    if cached:
        return json.loads(cached)

    team_data = await _load_team_data(db, scope)
    insights = await identify_team_insights(team_data)
    await redis_client.set(cache_key, json.dumps(insights, default=str), ex=TEAM_INSIGHTS_TTL_SECONDS)
    return insights


@router.post("/ask")
async def ask_team_question(
    query: AIQuery, db: AsyncSession = Depends(get_db), scope: Scope = Depends(get_scope)
):
    """
    Answer a natural language question about the team.
    Example: "Who needs coaching?" / "Who is ready for promotion?"
    """
    team_data = await _load_team_data(db, scope, query.employee_ids)
    answer = await answer_team_question(query.question, {"employees": team_data, "context": query.context})
    return {"answer": answer}


@router.post("/employee/{employee_id}/promotion-analysis")
async def analyze_promotion(
    employee_id: str,
    db: AsyncSession = Depends(get_db),
    _scope: Scope = Depends(require_employee_access),
):
    """
    Deep promotion readiness analysis for a specific employee.
    Returns: readiness level, evidence, gaps, and recommended timeline.
    """
    query = select(Employee).options(*DETAIL_RELATIONSHIPS, selectinload(Employee.role_profile)).where(
        Employee.id == employee_id
    )
    result = await db.execute(query)
    employee = result.scalar_one_or_none()
    if employee is None:
        raise HTTPException(404, "Employee not found")

    employee.tags = employee.tags or []
    employee_data = to_employee_detail(employee).model_dump(mode="json")
    next_level_criteria = (
        {
            "breadth_target": employee.role_profile.breadth_target,
            "depth_target": employee.role_profile.depth_target,
            "depth_skill_ids": employee.role_profile.depth_skill_ids,
        }
        if employee.role_profile
        else {}
    )
    return await analyze_promotion_readiness(employee_data, next_level_criteria)


@router.post("/employee/{employee_id}/summary")
async def generate_summary(
    employee_id: str,
    period: str = "quarterly",
    db: AsyncSession = Depends(get_db),
    _scope: Scope = Depends(require_employee_access),
):
    """
    Generate AI-powered performance summary.
    Suitable for performance review documentation.
    """
    query = select(Employee).options(*DETAIL_RELATIONSHIPS).where(Employee.id == employee_id)
    result = await db.execute(query)
    employee = result.scalar_one_or_none()
    if employee is None:
        raise HTTPException(404, "Employee not found")

    employee.tags = employee.tags or []
    employee_data = to_employee_detail(employee).model_dump(mode="json")
    summary = await generate_employee_summary(employee_data, period=period)
    return {"summary": summary}
