"""AI Insights endpoints."""
from fastapi import APIRouter, HTTPException, Depends
from typing import List
from app.schemas.schemas import AIQuery, AIInsightResponse

router = APIRouter()


@router.get("/", response_model=List[AIInsightResponse])
async def get_team_insights():
    """
    Return proactively identified team insights.
    Generated by AI service analyzing team performance data.
    Cached for 1 hour, refreshed on data change.
    """
    pass


@router.post("/ask")
async def ask_team_question(query: AIQuery):
    """
    Answer a natural language question about the team.
    Example: "Who needs coaching?" / "Who is ready for promotion?"
    """
    pass


@router.post("/employee/{employee_id}/promotion-analysis")
async def analyze_promotion(employee_id: str):
    """
    Deep promotion readiness analysis for a specific employee.
    Returns: readiness level, evidence, gaps, and recommended timeline.
    """
    pass


@router.post("/employee/{employee_id}/summary")
async def generate_summary(
    employee_id: str,
    period: str = "quarterly",
):
    """
    Generate AI-powered performance summary.
    Suitable for performance review documentation.
    """
    pass
