"""cascade deletes for employee-owned tables

Revision ID: 85bad54b9a90
Revises: fa9c52597a46
Create Date: 2026-09-01 15:53:58.979294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85bad54b9a90'
down_revision: Union[str, None] = 'fa9c52597a46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('certifications_employee_id_fkey', 'certifications', type_='foreignkey')
    op.create_foreign_key(None, 'certifications', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('conferences_employee_id_fkey', 'conferences', type_='foreignkey')
    op.create_foreign_key(None, 'conferences', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('director_notes_employee_id_fkey', 'director_notes', type_='foreignkey')
    op.create_foreign_key(None, 'director_notes', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('mentoring_relations_employee_id_fkey', 'mentoring_relations', type_='foreignkey')
    op.create_foreign_key(None, 'mentoring_relations', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('performance_scores_employee_id_fkey', 'performance_scores', type_='foreignkey')
    op.create_foreign_key(None, 'performance_scores', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('project_contributions_employee_id_fkey', 'project_contributions', type_='foreignkey')
    op.create_foreign_key(None, 'project_contributions', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('training_records_employee_id_fkey', 'training_records', type_='foreignkey')
    op.create_foreign_key(None, 'training_records', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_records', type_='foreignkey')
    op.create_foreign_key('training_records_employee_id_fkey', 'training_records', 'employees', ['employee_id'], ['id'])
    op.drop_constraint(None, 'project_contributions', type_='foreignkey')
    op.create_foreign_key('project_contributions_employee_id_fkey', 'project_contributions', 'employees', ['employee_id'], ['id'])
    op.drop_constraint(None, 'performance_scores', type_='foreignkey')
    op.create_foreign_key('performance_scores_employee_id_fkey', 'performance_scores', 'employees', ['employee_id'], ['id'])
    op.drop_constraint(None, 'mentoring_relations', type_='foreignkey')
    op.create_foreign_key('mentoring_relations_employee_id_fkey', 'mentoring_relations', 'employees', ['employee_id'], ['id'])
    op.drop_constraint(None, 'director_notes', type_='foreignkey')
    op.create_foreign_key('director_notes_employee_id_fkey', 'director_notes', 'employees', ['employee_id'], ['id'])
    op.drop_constraint(None, 'conferences', type_='foreignkey')
    op.create_foreign_key('conferences_employee_id_fkey', 'conferences', 'employees', ['employee_id'], ['id'])
    op.drop_constraint(None, 'certifications', type_='foreignkey')
    op.create_foreign_key('certifications_employee_id_fkey', 'certifications', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###
