"""assessment import batches

Revision ID: 970ade8f2e9b
Revises: 85bad54b9a90
Create Date: 2026-09-02 04:59:17.971746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '970ade8f2e9b'
down_revision: Union[str, None] = '85bad54b9a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_import_batches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('XLSX', 'CSV', 'FORM', name='assessmentimportsourceenum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPLIED', 'DISCARDED', name='assessmentimportstatusenum'), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_for_employee_id', sa.String(), nullable=True),
    sa.Column('rows_read', sa.Integer(), nullable=True),
    sa.Column('rows_applied', sa.Integer(), nullable=True),
    sa.Column('counts', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('rows', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['submitted_for_employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_import_batches_uploaded_by'), 'assessment_import_batches', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_import_batches_uploaded_by'), table_name='assessment_import_batches')
    op.drop_table('assessment_import_batches')
    # Postgres keeps an ENUM type after its last column is dropped, so a re-upgrade
    # would fail with "type already exists" unless they go too.
    sa.Enum(name='assessmentimportstatusenum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='assessmentimportsourceenum').drop(op.get_bind(), checkfirst=True)
