"""baseline schema

Revision ID: fa9c52597a46
Revises: 
Create Date: 2026-09-01 15:11:55.507856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa9c52597a46'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('primary_outcome', sa.Text(), nullable=True),
    sa.Column('depth_areas', sa.Text(), nullable=True),
    sa.Column('working_breadth', sa.Text(), nullable=True),
    sa.Column('ai_expectation', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('breadth_target', sa.Integer(), nullable=True),
    sa.Column('depth_target', sa.Integer(), nullable=True),
    sa.Column('depth_skill_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_weight_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('goal_achievement_weight', sa.Float(), nullable=True),
    sa.Column('project_contributions_weight', sa.Float(), nullable=True),
    sa.Column('professional_development_weight', sa.Float(), nullable=True),
    sa.Column('leadership_behaviors_weight', sa.Float(), nullable=True),
    sa.Column('collaboration_weight', sa.Float(), nullable=True),
    sa.Column('innovation_weight', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('subdomain', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('observable_capability', sa.Text(), nullable=True),
    sa.Column('example_evidence', sa.Text(), nullable=True),
    sa.Column('critical', sa.Boolean(), nullable=True),
    sa.Column('target_level', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('custom', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('skill_thresholds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('breadth', sa.Integer(), nullable=True),
    sa.Column('coverage', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('DIRECTOR', 'MANAGER', 'EMPLOYEE', 'ADMIN', name='userroleenum'), nullable=False),
    sa.Column('azure_oid', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_azure_oid'), 'users', ['azure_oid'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('manager_id', sa.String(), nullable=True),
    sa.Column('hire_date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('career_aspirations', sa.Text(), nullable=True),
    sa.Column('is_high_potential', sa.Boolean(), nullable=True),
    sa.Column('needs_coaching', sa.Boolean(), nullable=True),
    sa.Column('promotion_readiness', sa.Enum('READY_NOW', 'READY_6_MONTHS', 'READY_12_MONTHS', 'DEVELOPMENT_NEEDED', name='promotionreadinessenum'), nullable=True),
    sa.Column('role_profile_id', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['role_profile_id'], ['role_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=True)
    op.create_table('accomplishments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('TECHNICAL', 'LEADERSHIP', 'COLLABORATION', 'INNOVATION', 'OTHER', name='accomplishmentcategoryenum'), nullable=True),
    sa.Column('recognized_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accomplishments_employee_id'), 'accomplishments', ['employee_id'], unique=False)
    op.create_table('certifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('date_earned', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('credential_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certifications_employee_id'), 'certifications', ['employee_id'], unique=False)
    op.create_table('conferences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('key_learnings', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conferences_employee_id'), 'conferences', ['employee_id'], unique=False)
    op.create_table('director_notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('COACHING', 'RECOGNITION', 'LEADERSHIP_POTENTIAL', 'PERFORMANCE_OBSERVATION', 'CAREER_ASPIRATIONS', 'SUCCESSION_PLANNING', 'CONCERNS', 'FOLLOW_UP_ACTIONS', name='notecategoryenum'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_director_notes_employee_id'), 'director_notes', ['employee_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strategic_alignment', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='goalpriorityenum'), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'AT_RISK', 'COMPLETED', 'DEFERRED', name='goalstatusenum'), nullable=True),
    sa.Column('category', sa.Enum('QUARTERLY', 'ANNUAL', 'PERSONAL_DEVELOPMENT', 'ORGANIZATIONAL', name='goalcategoryenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_employee_id'), 'goals', ['employee_id'], unique=False)
    op.create_table('mentoring_relations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('partner_name', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('outcomes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('one_on_ones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('company_updates', sa.Text(), nullable=True),
    sa.Column('scorecard_highlights', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('ids', sa.JSON(), nullable=True),
    sa.Column('action_items', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_one_on_ones_employee_id'), 'one_on_ones', ['employee_id'], unique=False)
    op.create_table('performance_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('overall', sa.Float(), nullable=True),
    sa.Column('goal_achievement', sa.Float(), nullable=True),
    sa.Column('project_contributions', sa.Float(), nullable=True),
    sa.Column('professional_development', sa.Float(), nullable=True),
    sa.Column('leadership_behaviors', sa.Float(), nullable=True),
    sa.Column('collaboration', sa.Float(), nullable=True),
    sa.Column('innovation', sa.Float(), nullable=True),
    sa.Column('growth_score', sa.Float(), nullable=True),
    sa.Column('leadership_readiness', sa.Float(), nullable=True),
    sa.Column('promotion_readiness', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(), nullable=True),
    sa.Column('last_calculated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('project_contributions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('initiative', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_impact', sa.Text(), nullable=True),
    sa.Column('technical_impact', sa.Text(), nullable=True),
    sa.Column('leadership_score', sa.Integer(), nullable=True),
    sa.Column('collaboration_score', sa.Integer(), nullable=True),
    sa.Column('innovation_score', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('evidence_links', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_contributions_employee_id'), 'project_contributions', ['employee_id'], unique=False)
    op.create_table('skill_assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('self_rating', sa.Integer(), nullable=True),
    sa.Column('reviewer_rating', sa.Integer(), nullable=True),
    sa.Column('target_override', sa.Integer(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('evidence_url', sa.String(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(), nullable=True),
    sa.Column('assessed_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'skill_id', name='uq_employee_skill')
    )
    op.create_index(op.f('ix_skill_assessments_employee_id'), 'skill_assessments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_skill_assessments_skill_id'), 'skill_assessments', ['skill_id'], unique=False)
    op.create_table('training_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('course_name', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('hours_completed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_records_employee_id'), 'training_records', ['employee_id'], unique=False)
    op.create_table('development_plan_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('experience_assignment', sa.Text(), nullable=True),
    sa.Column('coach', sa.String(), nullable=True),
    sa.Column('course', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('success_evidence', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETE', name='developmentplanstatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('linked_goal_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_development_plan_items_employee_id'), 'development_plan_items', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_development_plan_items_employee_id'), table_name='development_plan_items')
    op.drop_table('development_plan_items')
    op.drop_index(op.f('ix_training_records_employee_id'), table_name='training_records')
    op.drop_table('training_records')
    op.drop_index(op.f('ix_skill_assessments_skill_id'), table_name='skill_assessments')
    op.drop_index(op.f('ix_skill_assessments_employee_id'), table_name='skill_assessments')
    op.drop_table('skill_assessments')
    op.drop_index(op.f('ix_project_contributions_employee_id'), table_name='project_contributions')
    op.drop_table('project_contributions')
    op.drop_table('performance_scores')
    op.drop_index(op.f('ix_one_on_ones_employee_id'), table_name='one_on_ones')
    op.drop_table('one_on_ones')
    op.drop_table('mentoring_relations')
    op.drop_index(op.f('ix_goals_employee_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_director_notes_employee_id'), table_name='director_notes')
    op.drop_table('director_notes')
    op.drop_index(op.f('ix_conferences_employee_id'), table_name='conferences')
    op.drop_table('conferences')
    op.drop_index(op.f('ix_certifications_employee_id'), table_name='certifications')
    op.drop_table('certifications')
    op.drop_index(op.f('ix_accomplishments_employee_id'), table_name='accomplishments')
    op.drop_table('accomplishments')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_azure_oid'), table_name='users')
    op.drop_table('users')
    op.drop_table('skill_thresholds')
    op.drop_table('skill_definitions')
    op.drop_table('score_weight_configs')
    op.drop_table('role_profiles')
    # ### end Alembic commands ###
